services:
  my-app:
    build:
      context: ./my-nest-js
      dockerfile: Dockerfile
      target: ${ENVIRONMENT}
    ports:
      - "3000:3000"
      - "80:80"
    develop:
      watch:
        - action: sync
          path: ./my-nest-js/src
          target: /app/src
        - action: sync+restart
          path: ./my-nest-js
          target: /app
        - action: rebuild
          path: ./my-nest-js/package.json